# Generated by Django 4.2.17 on 2024-12-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('lienPhoto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BilanBio',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('parametres', models.TextField()),
                ('est_complet', models.BooleanField(default=False)),
                ('est_resultat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('resume', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_creation', models.DateField()),
                ('createur_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BDD.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_etablissement', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('DPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.dpi')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nss', models.CharField(max_length=100)),
                ('nom_complet', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('lienPhoto', models.URLField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('statueMatrimonial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelMedical',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lienPhoto', models.URLField()),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('MEDECIN', 'Médecin'), ('RADIOLOGUE', 'Radiologue'), ('LABORANTIN', 'Laborantin'), ('INFIRMIER', 'Infirmier'), ('PHARMACIEN', 'Pharmacien')], default='MEDECIN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type_soins', models.CharField(choices=[('INFIRMIER', 'Infirmier'), ('RADIO', 'Radio'), ('LABO', 'Laboratoire')], default='INFIRMIER', max_length=10)),
                ('description', models.TextField()),
                ('etat_patient', models.CharField(max_length=100)),
                ('medicament', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.hospitalisation')),
                ('infermier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BDD.personnelmedical')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatRadio',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('piece_jointe', models.TextField()),
                ('date', models.DateField()),
                ('compte_rendu', models.TextField()),
                ('radiologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiologue', to='BDD.personnelmedical')),
                ('radiologue_compte_rendu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiologue_compte_rendu', to='BDD.personnelmedical')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatBio',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valeur_mesure', models.CharField(max_length=100)),
                ('date_mesure', models.DateField()),
                ('heure_mesure', models.TimeField()),
                ('parametre', models.CharField(max_length=100)),
                ('norme', models.CharField(max_length=50)),
                ('bilan_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.bilanbio')),
                ('laborantin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.personnelmedical')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('estValide', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.consultation')),
                ('pharmacien_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.personnelmedical')),
            ],
        ),
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('numero_adherent', models.IntegerField()),
                ('type_couverture', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='medecin_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.personnelmedical'),
        ),
        migrations.CreateModel(
            name='etablissement_personnel_medical',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.etablissement')),
                ('personnel_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.personnelmedical')),
            ],
        ),
        migrations.AddField(
            model_name='dpi',
            name='etablissement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.etablissement'),
        ),
        migrations.AddField(
            model_name='dpi',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BDD.patient'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='Hospitalisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.hospitalisation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.personnelmedical'),
        ),
        migrations.CreateModel(
            name='BilanRadio',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_radio', models.CharField(choices=[('RADIO', 'Radio'), ('SCANNER', 'Scanner'), ('IRM', 'IRM')], default='RADIO', max_length=10)),
                ('est_complet', models.BooleanField(default=False)),
                ('est_resultat', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('Consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BDD.consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.personnelmedical')),
                ('resultat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.resultatradio')),
            ],
        ),
        migrations.AddField(
            model_name='bilanbio',
            name='Consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BDD.consultation'),
        ),
        migrations.AddField(
            model_name='bilanbio',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.personnelmedical'),
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('DPI_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.dpi')),
            ],
        ),
    ]
