# Generated by Django 4.2.17 on 2024-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelmedical',
            name='role',
            field=models.CharField(choices=[('MEDECIN', 'Médecin'), ('RADIOLOGUE', 'Radiologue'), ('LABORANTIN', 'Laborantin'), ('INFIRMIER', 'Infirmier'), ('PHARMACIEN', 'Pharmacien')], default='MEDECIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='resultatbio',
            name='heure_mesure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='soins',
            name='heure',
            field=models.TimeField(),
        ),
    ]
