# Generated by Django 4.2.17 on 2024-12-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.patient'),
        ),
    ]
