# Generated by Django 4.2.17 on 2024-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0002_alter_dpi_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soins',
            name='type_soins',
            field=models.CharField(choices=[('INFIRMIER', 'Infirmier'), ("OBSERVATION D'ETAT", "Observation d'etat"), ('ADMINISTRATION DE MEDICAMENT', 'Administration de medicament'), ('AUTRES', 'Autres')], default='INFIRMIER', max_length=30),
        ),
    ]
