# Generated by Django 4.2.17 on 2024-12-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0003_alter_soins_type_soins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soins',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='soins',
            name='dose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soins',
            name='medicament',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
