# Generated by Django 4.2.17 on 2024-12-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0004_alter_soins_description_alter_soins_dose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanbio',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='bilanradio',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='resultatradio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='soins',
            name='etat_patient',
        ),
        migrations.AddField(
            model_name='contact',
            name='priorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bilanbio',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bilanbio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bilanbio',
            name='parametres',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bilanradio',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bilanradio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bilanradio',
            name='resultat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BDD.resultatradio'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='type',
            field=models.CharField(choices=[('HOPITAL', 'Hopital'), ('CLINIQUE', 'Clinique'), ('CABINET MEDICAL', 'Cabinet Medical')], default='HOPITAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='etablissement_personnel_medical',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mutuelle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='pharmacien_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BDD.personnelmedical'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personnelmedical',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personnelmedical',
            name='role',
            field=models.CharField(choices=[('MEDECIN', 'Medecin'), ('RADIOLOGUE', 'Radiologue'), ('LABORANTIN', 'Laborantin'), ('INFIRMIER', 'Infirmier'), ('PHARMACIEN', 'Pharmacien')], default='MEDECIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='resultatbio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultatradio',
            name='compte_rendu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resultatradio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultatradio',
            name='radiologue_compte_rendu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiologue_compte_rendu', to='BDD.personnelmedical'),
        ),
        migrations.AlterField(
            model_name='soins',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
