# Generated by Django 4.2.17 on 2024-12-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0005_remove_bilanbio_medecin_remove_bilanradio_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutuelle',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
