# Generated by Django 4.2.17 on 2024-12-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0006_alter_mutuelle_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='date',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='estTermier',
            field=models.BooleanField(default=False),
        ),
    ]
