# Generated by Django 4.2.17 on 2024-12-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0007_remove_ordonnance_date_ordonnance_esttermier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordonnance',
            old_name='estTermier',
            new_name='estTerminer',
        ),
    ]
