# Generated by Django 4.2.17 on 2024-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0008_rename_esttermier_ordonnance_estterminer'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
