# Generated by Django 4.2.17 on 2024-12-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0010_alter_admin_telephone_alter_contact_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mutuelle',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personnelmedical',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
