# Generated by Django 4.2.17 on 2024-12-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0011_alter_admin_telephone_alter_contact_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lieu_naissance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='statueMatrimonial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
