# Generated by Django 4.2.17 on 2024-12-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0013_dpi_medecin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanbio',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='bilanradio',
            name='medecin',
        ),
        migrations.AlterField(
            model_name='personnelmedical',
            name='role',
            field=models.CharField(choices=[('MEDECIN', 'Medecin'), ('RADIOLOGUE', 'Radiologue'), ('LABORANTIN', 'Laborantin'), ('INFIRMIER', 'Infirmier'), ('PHARMACIEN', 'Pharmacien')], default='MEDECIN', max_length=10),
        ),
    ]
