# Generated by Django 4.2.17 on 2025-01-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0014_alter_admin_id_alter_antecedent_id_alter_bilanbio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personnelmedical',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
