# Generated by Django 4.2.17 on 2025-01-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0016_alter_admin_id_alter_antecedent_id_alter_bilanbio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatbio',
            name='parametre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='soins',
            name='type_soins',
            field=models.CharField(choices=[('INFIRMIER', 'Infirmier'), ("OBSERVATION D'ETAT", "Observation d'etat"), ('ADMINISTRATION DE MEDICAMENT', 'Administration de medicament'), ('AUTRE', 'Autre')], default='INFIRMIER', max_length=30),
        ),
    ]
