# Generated by Django 5.1.4 on 2024-12-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelMedical',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('MEDECIN', 'Médecin'), ('RADIOLOGUE', 'Radiologue'), ('LABORANTIN', 'Laborantin'), ('INFIRMIER', 'Infirmier')], default='MEDECIN', max_length=10)),
            ],
        ),
    ]
